  - name: Recall virtual machines back to a PowerVC host
    hosts: localhost
    gather_facts: no
    tasks:
       - name: Recall virtual machines to the specified host
         ibm.powervc.host_recall:
            cloud: "CLOUD"
            host: "HOST_ID"
         register: result
       - debug:
            var: result

  - name: Recall virtual machines back to a PowerVC host
    hosts: localhost
    gather_facts: no
    vars:
     auth:
      auth_url: https://<POWERVC>:5000/v3
      project_name: PROJECT-NAME
      username: USERID
      password: PASSWORD
      project_domain_name: PROJECT_DOMAIN_NAME
      user_domain_name: USER_DOMAIN_NAME
    tasks:
       - name: Recall virtual machines to the specified host
         ibm.powervc.host_recall:
            auth: "{{ auth }}"
            host: "HOST_ID"
         register: result
       - debug:
            var: result